# Generated by Django 5.2.6 on 2025-09-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='environment_variables',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
